version: '3.3'

services:
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_DB}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    volumes:
      - mysql-service:/var/lib/mysql

volumes:
  mysql-service:
